### ISSUE TITLE
Building and running on linux

### ISSUE THREAD

**Issue by vizvamitra** [agonzalezv/coffeegrindsize#2]
Hello. Thanks for your work. I've used instructions in your readme and successfully built the program under ubuntu 16.04 with this command:

```bash
pyinstaller --onefile --windowed --noconfirm --add-binary='/usr/lib/x86_64-linux-gnu/libtk8.6.so':'tk' --add-binary='/usr/lib/x86_64-linux-gnu/libtcl8.6.so':'tcl' coffeegrindsize.py --clean --hidden-import="pkg_resources.py2_warn"
```

Thought it might be useful to someone

**Comment by agonzalezv** [comment]
@vizvamitra Thanks a lot for your contribution. I have added this to the README.
